POST http://localhost:8000/req
content-type: application/json

###############
PUT http://localhost:8000/req
content-type: application/json

{
    "valor":"123"
}
###############
DELETE http://localhost:8000/req
content-type: application/json

###############
PATCH http://localhost:8000/req
content-type: application/json

###############
OPTIONS http://localhost:8000/req
content-type: application/json
