@username=l@l.l
######
@pazword=123123123
######################
# @name password
POST http://localhost:8000/oauth/token HTTP/1.1
content-type: application/json
Accept: application/json

{
    "grant_type":"password",
    "client_id":4,
    "client_secret":"TlQ1AQEDCnioF7eM4uLVL8o7jsCrhb7YFISBx3KD",
    "username":"{{username}}",
    "password":"{{pazword}}",
    "scope":""
}
#####################
@password_token = {{password.response.body.access_token}}
#######################
GET http://localhost:8000/api/laratrust HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer {{password_token}}
#######################
GET http://localhost:8000/api/laratrust/1 HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer {{password_token}}
#######################
POST http://localhost:8000/api/laratrust HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer {{password_token}}
#######################
PUT http://localhost:8000/api/laratrust/1 HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer {{password_token}}
#######################
DELETE http://localhost:8000/api/laratrust/1 HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer {{password_token}}


