GET http://localhost:8000/api/test
###################
GET http://localhost:8000/api/products?page=1&fields=name,price&conditions=price=10
accept: application/json
Authorization: Basic c21pdGgubWFyY0BleGFtcGxlLmNvbTpwYXNzd29yZA==

###################
POST http://localhost:8000/api/products
content-type: application/json
accept: application/json

{
    "name": "Fanta Tangerina",
    "price": "8",
    "description": "Refrigerante de Cola",
    "slug": "pepsi"
}
###################
# Authorization: Basic to_b64(email:secret_without_bcrypt)
GET http://localhost:8000/api/products/3
content-type: application/json
accept: application/json
Authorization: Basic c21pdGgubWFyY0BleGFtcGxlLmNvbTpwYXNzd29yZA==

###################
PUT http://localhost:8000/api/products/2
content-type: application/json
accept: application/json

{
    "name": "Jesus Cola",
    "price": "10",
    "description": "Refrigerante do Maranhão",
    "slug": "coca"
}
###################
DELETE http://localhost:8000/api/products/2
###################
GET http://localhost:8000/api/users
###################
POST http://localhost:8000/api/users
###################
GET http://localhost:8000/api/users/1
###################
PUT http://localhost:8000/api/users/1
###################
DELETE http://localhost:8000/api/users/1
