 FROM ubuntu
    WORKDIR /root/

    RUN touch ./test.txt
    RUN touch ./test_2.txt
    RUN touch ./test_3.txt

    RUN mkdir -p ./testfolder
    WORKDIR /root/testfolder

    RUN mkdir -p ./child
    RUN mkdir -p ./child_1    
    