##########
GET http://localhost:8001/api/v1/category
Content-Type: application/json
Accept: application/json
Authorization: Basic d@d.d:123123123
##########
POST http://localhost:8001/api/v1/category
Content-Type: application/json
Accept: application/json
Authorization: Basic d@d.d:123123123

{
  "name" : "categoria",
  "description": "uma categoria qualquer",
  "slug": "hi"
}
##########
PUT http://localhost:8001/api/v1/category/1
Content-Type: application/json
Accept: application/json
Authorization: Basic d@d.d:123123123

{

  "name" : "name of category",
  "description": "category"
}
##########
DELETE http://localhost:8001/api/v1/category/1
Content-Type: application/json
Accept: application/json
Authorization: Basic d@d.d:123123123
##########
GET http://localhost:8001/api/v1/category/1
Content-Type: application/json
Accept: application/json
Authorization: Basic d@d.d:123123123
