###
POST http://localhost:8000/oauth/token HTTP/1.1
content-type: application/json
accept: application/json

{
    "grant_type": "password",
    "client_id": "2",
    "client_secret": "ZVjVfs9UhHGsg6V658RRt91tbufo2rSe7tY9AhuF",
    "username": "m@m.m",
    "password": "123123123"
}
###
POST http://localhost:8000/oauth/token HTTP/1.1
content-type:application/json
accept: application/json

{
    "grant_type": "client_credentials",
    "client_id": "5",
    "client_secret": "OUPKQzard59LRuIAwCWzqhTBLm72rrCBmEEILWE8",
    "scope": ""
}
