###
GET http://localhost:8000/api/user
accept: application/json
content-type: application/json
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0IiwianRpIjoiMDA2NjA0NTYwMjMzM2MwMDAxM2EzZmRmOWNjYmIzOTNkM2RmMGExYTJjYzQ0MmZkOWIzMzY4Y2MzMDhmNTk0YmJjYzMyMGFhODhkMmM3YTkiLCJpYXQiOjE2MDAwMjMwNjAsIm5iZiI6MTYwMDAyMzA2MCwiZXhwIjoxNjAxMzE5MDYwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.RwyymRVySs9l4mn_3JblxUndg8V6QA43Vbawcycj3Y2RHaAtTb5e6E6gBEEU4SFa0qHmLDNHxYsPGtO8riewvRPI07ojnNRc2NnJVwiJCOk-XkqI2dO20iSoVt5te9UfQgS5X_eT65fxVNN1DleNK4ze63kBjqJu6Ybyuz-x1xymeVAeY2EGxXiRZZfS9HHd856JkHFH4HBQpfnAaUuGF1f7CTzP2TCJWvE1Ig7Ht3PDKC0NPa8EQ27Cv0QvpUWLmnXyxHtBDEJa0gcsTM96KVhZiDVlurv20JSepFcBYuDa5A5n1xDAeXSYhtLA66U4lw0BFoAyiqPYEuE1kpYUwdynBWZl7-VvmPZOOIdy3yS-vDyWoU9sglSNgEeeUXsacmaVPcnQ7gtTfAJmXood0fdwrse5hZDBmefzOXtzk7eJf0k-o7cSGLz_1fc-mqToZvMdHcIQ-tllgBXDQ0Uki90Py9Yn2vwgxh-r0nFrCQ4h3ORqGeH6i7eQ5H35muYfAIHREJzkjj9APX1YKLH_9qqBTpF2rw_bYi39Ey9hnrRppjBO4qLsZZdYfZ5O7jRqKS4yU9Fa-5F_oO5ioDfkKRa3nWUgKkFSRQ_D6buUJ9S1L8soR5p2ggQwbyDLyyi6ew_sA322nLbnP6sRqKoEt6S4Aat3RSSqZbT_cEyAX-A

###
POST http://localhost:8000/api/user
accept: application/json
content-type: application/json
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0IiwianRpIjoiMDA2NjA0NTYwMjMzM2MwMDAxM2EzZmRmOWNjYmIzOTNkM2RmMGExYTJjYzQ0MmZkOWIzMzY4Y2MzMDhmNTk0YmJjYzMyMGFhODhkMmM3YTkiLCJpYXQiOjE2MDAwMjMwNjAsIm5iZiI6MTYwMDAyMzA2MCwiZXhwIjoxNjAxMzE5MDYwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.RwyymRVySs9l4mn_3JblxUndg8V6QA43Vbawcycj3Y2RHaAtTb5e6E6gBEEU4SFa0qHmLDNHxYsPGtO8riewvRPI07ojnNRc2NnJVwiJCOk-XkqI2dO20iSoVt5te9UfQgS5X_eT65fxVNN1DleNK4ze63kBjqJu6Ybyuz-x1xymeVAeY2EGxXiRZZfS9HHd856JkHFH4HBQpfnAaUuGF1f7CTzP2TCJWvE1Ig7Ht3PDKC0NPa8EQ27Cv0QvpUWLmnXyxHtBDEJa0gcsTM96KVhZiDVlurv20JSepFcBYuDa5A5n1xDAeXSYhtLA66U4lw0BFoAyiqPYEuE1kpYUwdynBWZl7-VvmPZOOIdy3yS-vDyWoU9sglSNgEeeUXsacmaVPcnQ7gtTfAJmXood0fdwrse5hZDBmefzOXtzk7eJf0k-o7cSGLz_1fc-mqToZvMdHcIQ-tllgBXDQ0Uki90Py9Yn2vwgxh-r0nFrCQ4h3ORqGeH6i7eQ5H35muYfAIHREJzkjj9APX1YKLH_9qqBTpF2rw_bYi39Ey9hnrRppjBO4qLsZZdYfZ5O7jRqKS4yU9Fa-5F_oO5ioDfkKRa3nWUgKkFSRQ_D6buUJ9S1L8soR5p2ggQwbyDLyyi6ew_sA322nLbnP6sRqKoEt6S4Aat3RSSqZbT_cEyAX-A

{
    "var": "David"
}
