# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  contatos-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql
    container_name: contatos-mysql
    volumes:
      - contatos-mysql-data:/var/lib/mysql
    ports:
      - "4242:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=contatos
      - MYSQL_DATABASE=contatos
      - MYSQL_USER=contatos
      - MYSQL_PASSWORD=contatos

  # PHP
  app:
    image: ambientum/php:7.2-nginx
    container_name: contatos-app
    volumes:
      - .:/var/www/app
    ports:
      - "1618:8080"
    links:
      - mysql